### PR TITLE
Add failing route with regular expression

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by harikt** [comment]
Hi @ralphschindler , 

any thoughts on this PR and #6

**Comment by ralphschindler** [comment]
I have an additional test for this, looks like the code is fine, just needs a more expansive regex.

**Comment by ralphschindler** [comment]
So, this is the diff I was thinking of committing:
```diff
diff --git a/tests/Router/HttpRouteTest.php b/tests/Router/HttpRouteTest.php
index d29c864..5dcc80e 100644
--- a/tests/Router/HttpRouteTest.php
+++ b/tests/Router/HttpRouteTest.php
@@ -118,12 +118,18 @@ class HttpRouteTest extends \PHPUnit_Framework_TestCase
                 ['uri' => '/hello/thing', 'method' => 'GET'],
                 false
             ],
-            // match required param with regex validation, provided
+            // failed match required param with regex validation, provided
             [
-                '/hello/:id#\d#',
+                '/hello/:id#^\d+$#',
                 ['uri' => '/hello/456ggg', 'method' => 'GET'],
                 false
             ],
+            // successful match required param with regex validation, provided
+            [
+                '/hello/:id#^\d+$#',
+                ['uri' => '/hello/456', 'method' => 'GET'],
+                ['id' => '456']
+            ],
             // match literal, no implied trailing slash
             [
                 ['/hello', [], [], false],
```
I guess the question is whether or not url validators should automatically be anchored front and back.

**Comment by harikt** [comment]
> I guess the question is whether or not url validators should automatically be anchored front and back

Don't think I get you. What do you mean anchored front and back.

**Comment by harikt** [comment]
ping @ralphschindler . Any progress ?

**Comment by harikt** [comment]
I am ok with this particular change you mentioned. Do you think you need a PR or can merge yours ?

**Pull request closed without merging**
